backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Business Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
